import { Container } from "../../node_modules/pixi.js/lib/scene/container/Container"
import { Graphics } from "../../node_modules/pixi.js/lib/scene/graphics/shared/Graphics"
import { Sprite } from "../../node_modules/pixi.js/lib/scene/sprite/Sprite"
import { Text } from "../../node_modules/pixi.js/lib/scene/text/Text"

export type EdgeMarkerTypes = "arrow" | "hollowArrow" | "none"
export type OrthogonalEdgePositions = "top" | "right" | "bottom" | "left"

/** Node IDs can be either strings or number */
export type NodeID = string | number

/** Shapes that nodes can be of */
export type NodeShape =
	| {
			id: "rectangle"
			height: number
			width: number
			radius: number
	  }
	| {
			id: "circle"
			radius: number
	  }

/** Minimum configuration nodes */
export interface IBasicNode {
	/** Unique identifier for the node */
	id: NodeID
}

/** Minimum configuration edges */
export interface IBasicEdge {
	/** Where the edge is directed from */
	sourceNode: NodeID
	/** Where the edge is directed to */
	targetNode: NodeID
}

/** Internal node structure */
export interface IGraphNode extends IBasicNode {
	/** Template for object, used for shared properties */
	template?: string
	/** Index for the node in the list of nodes */
	index: number
	/** Shape of the node */
	shape: NodeShape
	/** Mass of the node */
	mass: number
	/** X coordinate */
	x: number
	/** Y coordinate */
	y: number
	/** Fixed X coordinate (always trumps X) */
	fx?: number | null
	/** Fixed Y coordinate (always trumps Y) */
	fy?: number | null
	/** Node velocity (current movement) on the X-axis  */
	vx: number
	/** Node velocity (current movement) on the Y-axis */
	vy: number
	/** Renderer options */
	rendererOptions?: {
		/** Optional icon URL */
		icon?: string
		/** Background color of the node */
		backgroundColor?: string
		/** Text color of the node */
		textColor?: string
		/** Should the border be dotted? */
		dotted?: boolean
	}
	/** Renderer internals (generated by the renderer) */
	rendererInternals?: {
		container: Container
		node: Graphics
		text: null
		icon: null
		selected: Graphics
		isFocused: false
		isSelected: false
	}
}

/** Internal edge structure */
export interface IGraphEdge extends IBasicEdge {
	/** Template for object, used for shared properties */
	template?: string
	/** Index for the edge in the list of edges */
	index: number
	/** Actual source node object */
	source: IGraphNode
	/** Actual target node object */
	target: IGraphNode
	/** Strength of the edge */
	strength: number
	/** How long is the edge */
	distance: number
	/** How long is the visible section of the edge? */
	visibleDistance: number
	/** Weight of the edge, typically used in path finding and community computations to determine the significance of the edge */
	weight: number
	/** Renderer options */
	rendererOptions?: {
		/** Should the edge be dotted? */
		dotted?: boolean
		/** Color of the edge */
		color?: string
		/** Background color of the edge label */
		labelBackgroundColor?: string
		/** Text color of the edge label */
		labelTextColor?: string
		/** Is the label interactive? */
		isInteractive?: boolean
		/** In an orthogonal line type this can be used to control where the lines start and end */
		sourceEdgePosition?: OrthogonalEdgePositions
		/** In an orthogonal line type this can be used to control where the lines start and end */
		targetEdgePosition?: OrthogonalEdgePositions
		/** Marker to be drawn on the source side of the edge */
		markerSource?: EdgeMarkerTypes
		/** Marker to be drawn on the target side of the edge */
		markerTarget?: EdgeMarkerTypes
	}
	/** Renderer internals (generated by the renderer) */
	rendererInternals?: {
		container: Container
		line: Graphics
		markerSource: Sprite
		markerTarget: Sprite
		text: null | Text
		edgeCounter: {
			total: number
			index: number
		}
	}
}

export type LayoutNode = Pick<IGraphNode, "id" | "index" | "shape" | "template" | "mass" | "x" | "y" | "fx" | "fy" | "vx" | "vy">
export type RendererNode = Pick<IGraphNode, "id" | "shape" | "template" | "x" | "y" | "rendererOptions">
export type InternalRendererNode = RendererNode & Pick<IGraphNode, "rendererInternals">

export type LayoutEdge = Pick<
	IGraphEdge,
	"distance" | "index" | "source" | "sourceNode" | "target" | "targetNode" | "template" | "strength" | "visibleDistance" | "weight"
>
export type RendererEdge = Pick<
	IGraphEdge,
	"distance" | "source" | "sourceNode" | "target" | "targetNode" | "template" | "visibleDistance" | "weight" | "rendererOptions"
>
export type InternalRendererEdge = RendererEdge & Pick<IGraphEdge, "rendererInternals">

export type DraftNode = Partial<IGraphNode> & IBasicNode
export type DraftEdge = Partial<IGraphEdge> & IBasicEdge

export type NodeTemplate = Partial<Pick<IGraphNode, "shape" | "mass" | "rendererOptions">>
export type EdgeTemplate = Partial<Pick<IGraphEdge, "strength" | "weight" | "distance" | "visibleDistance" | "rendererOptions">>
export interface GraphObjectTemplates {
	nodes: {
		id: string
		template: NodeTemplate
	}[]
	edges: {
		id: string
		template: EdgeTemplate
	}[]
}
